parameters:
#    dev_trw_lb.example.class: DevTrw\LbBundle\DevTrwLbBundle\Example

services:
#    dev_trw_lb.example:
#        class: %dev_trw_lb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
